# Generated by Django 4.1.7 on 2023-04-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0002_initial'),
    ]

    operations = [
    ]
