# Generated by Django 4.1.7 on 2023-04-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0004_subpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
