# Generated by Django 4.1.7 on 2023-04-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0006_alter_subpost_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subpost',
            table='subpost',
        ),
    ]
