# Generated by Django 4.1.7 on 2023-04-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0009_alter_subpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
