# Generated by Django 4.2 on 2023-04-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0019_alter_subpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
